[project]
name = "clues-by-sam-solver"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "playwright>=1.57.0",
    "z3-solver>=4.15.3.0",
]
